// Package publisher provides primitives to interact with the asyncapi
//
// Code generated by https://github.com/asyncapi/generator/ DO NOT EDIT.
package publisher

import (
	"context"
	"encoding/json"

	"github.com/ThreeDotsLabs/watermill"
	"github.com/ThreeDotsLabs/watermill/message"
	"github.com/pkg/errors"
)

func NewPublisherClient(pub message.Publisher) *PublisherClient {
	return &PublisherClient{
		publisher: pub,
	}
}

type PublisherClient struct {
	publisher message.Publisher
}

func (c PublisherClient) TaskCreated(ctx context.Context, e TaskCreated) error {
	data, err := json.Marshal(e)
	if err != nil {
		return errors.Wrap(err, "marshal data")
	}

	return c.publisher.Publish("tasks-cud.created", message.NewMessage(watermill.NewShortUUID(), data))
}

func (c PublisherClient) TaskUpdated(ctx context.Context, e TaskUpdated) error {
	data, err := json.Marshal(e)
	if err != nil {
		return errors.Wrap(err, "marshal data")
	}

	return c.publisher.Publish("tasks-cud.updated", message.NewMessage(watermill.NewShortUUID(), data))
}
