// Package async provides primitives to interact with the asyncapi
//
// Code generated by https://github.com/asyncapi/generator/ DO NOT EDIT.
package async

type ReAssignTasks struct {
	TriggeredByUser string `json:"triggered_by_user"`
}
