// Package async provides primitives to interact with the asyncapi
//
// Code generated by https://github.com/asyncapi/generator/ DO NOT EDIT.
package async

import (
	"context"
	"encoding/json"

	"github.com/ThreeDotsLabs/watermill/message"
	"github.com/pkg/errors"
)

func Register(application ServerInterface, router *message.Router, subscriber message.Subscriber) error {
	asyncServer := ServerInterfaceWrapper{app: application}

	router.AddNoPublisherHandler(
		"tasks.reassign",
		"tasks.reassign",
		subscriber,
		asyncServer.ReAssignTasks,
	)

	return nil
}

type ServerInterface interface {
	ReAssignTasks(ctx context.Context, e ReAssignTasks) error
}

type ServerInterfaceWrapper struct {
	app ServerInterface
}

func (s ServerInterfaceWrapper) ReAssignTasks(msg *message.Message) error {
	event := &ReAssignTasks{}

	err := json.Unmarshal(msg.Payload, &event)
	if err != nil {
		return errors.Wrap(err, "parse event")
	}

	return s.app.ReAssignTasks(msg.Context(), *event)
}
