// Package adapters provides primitives to interact with the asyncapi
//
// Code generated by https://github.com/asyncapi/generator/ DO NOT EDIT.
package adapters

import "time"

type TaskEstimated struct {
	Id            string    `json:"id"`
	AssignedPrice float32   `json:"assignedPrice"`
	CompetedPrice float32   `json:"competedPrice"`
	SentAt        time.Time `json:"sentAt"`
}
