// Package publisher provides primitives to interact with the asyncapi
//
// Code generated by https://github.com/asyncapi/generator/ DO NOT EDIT.
package publisher

type TransactionCreated struct {
	Uid     string  `json:"uid"`
	UserUid string  `json:"user_uid"`
	Amount  float32 `json:"amount"`
	Reason  string  `json:"reason"`
}
