// Package publisher provides primitives to interact with the asyncapi
//
// Code generated by https://github.com/asyncapi/generator/ DO NOT EDIT.
package publisher

type TaskAssigned struct {
	PublicId string `json:"public_id"`
	UserId   string `json:"user_id"`
}
type TaskCreated struct {
	PublicId string `json:"public_id"`
}
type TaskCompleted struct {
	PublicId string `json:"public_id"`
}
